### ISSUE TITLE
what is the purpose of this project?

### ISSUE THREAD

**Issue by Myeongjoon** [breadkingdom/SangJo.Algorithm.FE#2]
algorithm site like https://www.acmicpc.net/?
or recruiting web site https://www.hackerrank.com/?

**Comment by Myeongjoon** [comment]
how about algorithm portal like https://www.geeksforgeeks.org/

**Comment by breadkingdom** [comment]
Ok. Let's go!

**Comment by Myeongjoon** [comment]
very good
